config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :exercises
  resources :routines

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :user
  has_many :routine_exercises, dependent: :destroy
  has_many :routines, through: :routine_exercises
  has_one_attached :photo

  validates :name, presence: true
  validates :category, presence: true


end

app/models/routine.rb
class Routine < ApplicationRecord
  belongs_to :user
  has_many :routine_exercises, dependent: :destroy
  has_many :exercises, through: :routine_exercises

  CATEGORIES = ['Soccer', 'Basketball', 'Gym', 'Yoga', 'Running'].freeze

  CATEGORY_IMAGES = {
    'Soccer' => 'categories/soccer.jpg',
    'Basketball' => 'categories/basketball.jpg',
    'Gym' => 'categories/gym.jpg',
    'Yoga' => 'categories/yoga.jpg',
    'Running' => 'categories/running.jpg'
  }.freeze

  def category_image
    CATEGORY_IMAGES[category]
  end

  def ordered_exercises
    exercises.joins(:routine_exercises).order('routine_exercises.position')
  end
end

app/models/routine_exercise.rb
class RoutineExercise < ApplicationRecord
  belongs_to :routine
  belongs_to :exercise

  validates :routine_id, uniqueness: { scope: :exercise_id }

  default_scope { order(:position) }

end

app/models/user.rb
class User < ApplicationRecord
  has_many :exercises
  has_many :routines

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_exercise, only: [:show, :edit, :update, :destroy]

  def index
    @exercises = current_user.exercises
  end

  def show
  end

  def new
    @exercise = Exercise.new
  end

  def create
    @exercise = current_user.exercises.build(exercise_params)
    if @exercise.save
      redirect_to exercises_path, notice: 'Exercise was successfully created.'
    else
      render :new
    end
  end

  def edit
    # Código para editar el ejercicio si es necesario
  end

  def update
    if @exercise.update(exercise_params)
      redirect_to exercise_path(@exercise), notice: 'Exercise was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @exercise.destroy
    redirect_to exercises_path, notice: 'Exercise was successfully deleted.'
  end

  private

  def set_exercise
    @exercise = current_user.exercises.find(params[:id])
  end

  def exercise_params
    params.require(:exercise).permit(:name, :duration, :sets, :repetitions, :description, :photo, :category)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_routine, only: [:show, :edit, :update, :destroy]

  def index
    @routines = current_user.routines.includes(:exercises)
  end

  def show
    @routine = Routine.find(params[:id])
    @exercises = @routine.ordered_exercises
  end


  def new
    @routine = Routine.new
    @exercises = current_user.exercises
  end

  def create
    @routine = current_user.routines.build(routine_params)
    if @routine.save
      exercise_ids = params[:routine][:exercise_ids].flat_map { |id| id.split(',') }.map(&:to_i)
      exercise_ids.each_with_index do |id, index|
        RoutineExercise.create!(routine_id: @routine.id, exercise_id: id, position: index + 1) unless RoutineExercise.exists?(routine_id: @routine.id, exercise_id: id)
      end
      redirect_to routines_path, notice: 'Routine was successfully created.'
    else
      @exercises = current_user.exercises
      render :new
    end
  end

  def edit
    @exercises = current_user.exercises
  end

  def update
    if @routine.update(routine_params)
      redirect_to @routine, notice: 'Routine was successfully updated.'
    else
      @exercises = current_user.exercises
      render :edit
    end
  end

  def destroy
    @routine.destroy
    redirect_to routines_path, notice: 'Routine was successfully deleted.'
  end

  private

  def set_routine
    @routine = Routine.find(params[:id])
  end

  def routine_params
    params.require(:routine).permit(:name, :category, exercise_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users/sessions_helper.rb
module Users::SessionsHelper
end

app/views/exercises/_form.html.erb
<!-- app/views/exercises/_form.html.erb -->
<%= form_with model: exercise, local: true, class: "needs-validation" do |form| %>
  <div class="row justify-content-center">
    <div class="col-3">
      <div class="mb-3">
        <%= form.label :name, class: "form-label" %>
        <%= form.text_field :name, class: "form-control", required: true %>
      </div>
    </div>
    <div class="col-3">
      <div class="mb-3">
        <%= form.label :photo, class: "form-label" %>
        <%= form.file_field :photo, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="row justify-content-center">
    <div class="col-2">
      <div class="mb-3">
        <%= form.label :sets, class: "form-label" %>
        <%= form.number_field :sets, class: "form-control" %>
      </div>
    </div>
    <div class="col-2">
      <div class="mb-3">
        <%= form.label :repetitions, class: "form-label" %>
        <%= form.number_field :repetitions, class: "form-control" %>
      </div>
    </div>
    <div class="col-2">
      <div class="mb-3">
        <%= form.label :duration, class: "form-label" %>
        <%= form.number_field :duration, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="row justify-content-center">
    <div class="col-6">
      <div class="mb-3">
        <%= form.label :category, class: "form-label" %>
        <%= form.select :category, options_for_select(["Soccer", "Basketball", "Gym", "Yoga", "Running"], exercise.category), { prompt: "Select Category" }, { class: "form-control" } %>
      </div>
    </div>
  </div>

  <div class="row justify-content-center">
    <div class="col-6">
      <div class="mb-3">
        <%= form.label :description, class: "form-label" %>
        <%= form.text_area :description, class: "form-control", rows: 3 %>
      </div>
    </div>
  </div>

  <div class="row justify-content-center">
    <div class="col-6">
      <div class="d-grid">
        <%= form.submit submit_text, class: "btn-custom" %>
      </div>
    </div>
  </div>
<% end %>

app/views/exercises/edit.html.erb
<!-- app/views/exercises/edit.html.erb -->
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-6">
      <h1 class="mb-4">Edit Exercise</h1>
    </div>
  </div>

  <%= render 'form', exercise: @exercise, submit_text: 'Update Exercise' %>
</div>

app/views/exercises/index.html.erb
<div class="container mt-5">
  <div class="row align-items-center mb-5">
    <div class="col-10 align-items-center">
      <h1 class="page-title">My Exercises</h1>
    </div>
     <div class="col-2">
     <%= link_to 'New Exercise', new_exercise_path, class: "btn-custom mb-4" %>
     </div>
  </div>
  <div class="row">
    <% @exercises.each do |exercise| %>
      <div class="col-md-3 d-flex">
        <%= link_to exercise_path(exercise), class: "custom-card-link mb-4" do %>
          <div class="custom-card  shadow-sm">
            <% if exercise.photo.attached? %>
              <%= image_tag exercise.photo, class: "card-img-top" %>
            <% end %>
            <div class="card-body d-flex flex-column">
              <h5 class="card-title"><%= exercise.name %></h5>
              <% if exercise.duration.present? %>
                <p class="card-text"><%= exercise.duration %> minutes</p>
              <% end %>
              <% if exercise.sets.present? %>
                <p class="card-text"><strong>Sets:</strong> <%= exercise.sets %></p>
              <% end %>
              <% if exercise.repetitions.present? %>
                <p class="card-text"><strong>Repetitions:</strong> <%= exercise.repetitions %></p>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/exercises/new.html.erb
<!-- app/views/exercises/new.html.erb -->
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-6">
      <h1 class="mb-4">New Exercise</h1>
    </div>
  </div>

  <%= render 'form', exercise: @exercise, submit_text: 'Create Exercise' %>
</div>

app/views/exercises/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-6">
      <% if @exercise.photo.attached? %>
        <%= image_tag @exercise.photo, class: "exercise-photo" %>
      <% else %>
        <div class="no-photo">No Photo</div>
      <% end %>
    </div>
    <div class="col-3">
      <% if @exercise.duration.present? %>
        <div class="detail-item">
          <span class="detail-title">Duration</span>
          <span class="detail-value"><%= @exercise.duration %> minutes</span>
        </div>
      <% end %>
      <% if @exercise.sets.present? %>
        <div class="detail-item">
          <span class="detail-title">Sets</span>
          <span class="detail-value"><%= @exercise.sets %></span>
        </div>
      <% end %>
      <% if @exercise.repetitions.present? %>
        <div class="detail-item">
          <span class="detail-title">Reps</span>
          <span class="detail-value"><%= @exercise.repetitions %></span>
        </div>
      <% end %>
    </div>
    <div class="col d-flex justify-content-end align-items-start">
        <%= link_to 'Edit', edit_exercise_path(@exercise), class: 'btn-custom me-1' %>
        <%= link_to "Delete", exercise_path(@exercise),
            data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' },
            class: "btn-delete" %>
      </div>
    <div class="name-section mt-5">
      <h2><%= @exercise.name %></h2>
    </div>
    <div class="description-section">
      <p><%= simple_format(@exercise.description) %></p>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="home-banner">
  <div class="container">
    <div class="row">
      <div class="col-6">
        <h1>Workout World</h1>
        <p>Your ultimate app for managing your sports training routines and exercises.</p>
        <%= link_to 'Get Started', new_user_registration_path, class: 'btn btn-custom' %>
      </div>
    </div>
  </div>
</div>

<div class="container my-5 py-5 section1">
  <div class="row">
    <h2 class="text-center motivation-phrase mb-5">
      Elevate Your Training
    </h2>
  </div>
  <div class="row mt-5">
    <div class="col-md-4 text-center">
     <%= image_tag 'phone1.png', alt: 'Track Your Progress', class: 'phone-img mb-3' %>
      <h3>Track Your Progress</h3>
      <p>Keep track of your exercises and routines with ease.</p>
    </div>
    <div class="col-md-4 text-center">
      <%= image_tag 'mackbook.png', alt: 'Custom Routines', class: 'img-fluid mb-3' %>
      <h3>Custom Routines</h3>
      <p>Create and manage custom routines tailored to your needs.</p>
    </div>
    <div class="col-md-4 text-center">
      <%= image_tag '', alt: 'Stay Motivated', class: 'img-fluid mb-3' %>
      <h3>Stay Motivated</h3>
      <p>Set goals and stay motivated with our intuitive platform.</p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SportsApp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@400..900&family=Staatliches&display=swap" rel="stylesheet">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-links-track': 'reload' %>
  <%= javascript_importmap_tags %>
</head>

<body class="d-flex flex-column min-vh-100">
  <%= render 'shared/navbar' %>
    <%= yield %>
  <%= render 'shared/footer' %>
</body>
</html>

app/views/routines/_form.html.erb
<%= form_with model: @routine, local: true, class: 'form-group' do |form| %>

<div class="row align-items-end">
  <div class="col-4">
      <%= form.label :name, class: 'form-label' %>
      <%= form.text_field :name, class: 'form-control' %>
  </div>
  <div class="col-3">
      <%= form.label :category, class: 'form-label' %>
      <%= form.select :category, Routine::CATEGORIES, {}, { class: 'custom-select' } %>
  </div>
  <div class="col-2">
     <%= form.submit 'Create Routine', class: 'btn-custom' %>
  </div>
</div>

  <h2 class="mt-5 mb-4">Select Exercises</h2>

  <div class="row">
    <% @exercises.each do |exercise| %>
      <div class="col-md-3 d-flex align-items-stretch">
        <div class="custom-card mb-4 shadow-sm exercise-card" data-exercise-id="<%= exercise.id %>">
          <% if exercise.photo.attached? %>
            <%= image_tag exercise.photo, class: "card-img-top" %>
          <% end %>
          <div class="card-body d-flex flex-column">
            <h5 class="card-title"><%= exercise.name %></h5>
            <% if exercise.duration.present? %>
              <p class="card-text"><strong>Duration:</strong> <%= exercise.duration %> minutes</p>
            <% end %>
            <% if exercise.sets.present? %>
              <p class="card-text"><strong>Sets:</strong> <%= exercise.sets %></p>
            <% end %>
            <% if exercise.repetitions.present? %>
              <p class="card-text"><strong>Repetitions:</strong> <%= exercise.repetitions %></p>
            <% end %>
            <span class="exercise-number badge"></span>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <%= form.hidden_field :exercise_ids, id: 'selected-exercises', multiple: true %>

<% end %>

app/views/routines/edit.html.erb
<div class="container">
  <h1 class="mb-4">Edit Routine</h1>
  <%= render 'form', routine: @routine %>
</div>

app/views/routines/index.html.erb
<div class="container mt-5">
  <div class="row align-items-center mb-5">
    <div class="col-10 align-items-center">
      <h1 class="page-title">My Routines</h1>
    </div>
    <div class="col-2">
      <%= link_to 'New Routine', new_routine_path, class: "btn btn-custom mb-4" %>
    </div>
  </div>
  <div class="row">
    <% @routines.each do |routine| %>
      <div class="col-md-3 d-flex align-items-stretch">
        <%= link_to routine_path(routine), class: "category-card-link" do %>
          <div class="category-card mb-4 shadow-sm" style="background-image: url(<%= asset_path(routine.category_image) %>);">
            <div class="card-body d-flex flex-column">
              <h5 class="card-title"><%= routine.name %></h5>
              <ul class="card-text">
                <% reordered_exercises = routine.ordered_exercises.rotate(-1) %>
                <% reordered_exercises.each do |exercise| %>
                  <li><%= exercise.name %></li>
                <% end %>
              </ul>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/routines/new.html.erb
<div class="container mt-5">
  <h1 class="mb-4">Create a Routine</h1>
  <%= render 'form', routine: @routine %>
</div>

app/views/routines/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col">
      <h1 class="mb-4"><%= @routine.name %> - <%= @routine.category %></h1>
    </div>
    <div class="col d-flex justify-content-end align-items-start">
      <%= link_to 'Edit', edit_routine_path(@routine), class: 'btn-custom me-1' %>
      <%= link_to "Delete", routine_path(@routine),
          data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' },
          class: "btn-delete" %>
    </div>
  </div>
  <div class="row mb-4">
    <div class="col-12">
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, fugiat alias. Hic fugiat accusamus amet rerum et repellat vel. Nostrum possimus ipsam, esse ipsa repellat dolore, sit fugiat quidem exercitationem voluptas blanditiis maiores quibusdam doloribus non nam laudantium incidunt, alias optio placeat fuga recusandae vitae commodi? Iste tempore deleniti dolores?</p>
    </div>
  </div>

  <% reordered_exercises = @exercises.rotate(-1) %>  <!-- Mueve el primer elemento al final -->

  <div class="row">
    <% reordered_exercises.each_with_index do |exercise, index| %>
      <div class="col-md-4">
        <%= link_to exercise_path(exercise), class: "exercise-card-link" do %>
          <div class="routine-exercise-card position-relative mb-4">
            <div class="number-badge position-absolute">
              <span><%= index + 1 %></span>
            </div>
            <% if exercise.photo.attached? %>
              <%= image_tag exercise.photo, class: "exercise-photo img-fluid" %>
            <% else %>
              <div class="no-photo">No Photo</div>
            <% end %>
            <div class="card-body">
              <h5 class="card-title"><%= exercise.name %></h5>
              <ul class="list-unstyled">
                <% if exercise.sets.present? %>
                  <li><strong>Sets:</strong> <%= exercise.sets %></li>
                <% end %>
                <% if exercise.repetitions.present? %>
                  <li><strong>Reps:</strong> <%= exercise.repetitions %></li>
                <% end %>
                <% if exercise.duration.present? %>
                  <li><%= exercise.duration %> minutes</li>
                <% end %>
              </ul>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="mt-auto py-3 bg-light">
  <div class="container">
    <span class="text-muted">Place sticky footer content here.</span>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-custom p-3">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag 'logotipo.png', alt: 'SportsApp Logo', class: 'd-inline-block align-text-top logo-img' %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.email %>
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <li><%= link_to 'My Routines', routines_path, class: 'dropdown-item' %></li>
              <li><%= link_to 'My Exercises', exercises_path, class: 'dropdown-item' %></li>
              <li><hr class="dropdown-divider"></li>
              <li>
                <%= link_to "Log Out", destroy_user_session_path,
                  data: { turbo_method: :delete },
                  class: "dropdown-item" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Log in', new_user_session_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>